<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CEOverPressure</AssemblyName>
    <RootNamespace>CEOverPressure</RootNamespace>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../../1.6/Assemblies/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PressureModel.fs" />
    <Compile Include="Defs.fs" />
    <Compile Include="ModSettings.fs" />
    <Compile Include="Overpressure.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.7.2" ExcludeAssets="runtime" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" PrivateAssets="All" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CombatExtended">
      <HintPath>$(COMBAT_EXTENDED_DIR)/Assemblies/CombatExtended.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
